/* Tadpole — GLES 1.x entry points we have not implemented.
 *
 * GENERATED by tools/gen-gl-stubs.py — do not edit by hand. To change what a
 * stub does, change the template in that script; a hand edit here survives
 * exactly until the next `gen-gl-stubs.py --write`.
 *
 * These exist so a guest can never hit an unresolved symbol. Since our library
 * is reached as libopengles_lite.so, which is the name native titles link, a
 * missing entry point is fatal at LOAD time:
 *     AppManager: can't resolve symbol 'glLightx'
 * Real implementations live in tadpole_gles_core.c and take precedence;
 * anything left here does no GL work at all.
 *
 * WHAT THEY DO INSTEAD OF NOTHING. Each one counts its calls and says so — once
 * at any volume, every time under TADPOLE_GL_DEBUG=1, and fatally under
 * TADPOLE_GL_DEBUG=2. The count matters as much as the name: it turns "108
 * entry points are missing" into "this title called these six, 1200 times a
 * frame", which is the difference between a list and a work queue.
 *
 * They still take no arguments. That is deliberate and it is safe: the caller
 * cleans up its own stack under AAPCS, so a (void) callee simply ignores
 * whatever was passed. It is also why a stub can never USE those arguments —
 * implementing one means moving it to tadpole_gles_core.c with a real
 * signature, not filling in a body here.
 */
#include "tadpole_gles_debug.h"

typedef unsigned int  GLenum;
typedef unsigned int  GLbitfield;
typedef unsigned char GLboolean;

void glBindFramebufferOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glBindFramebufferOES", &hits); }
void glBindRenderbufferOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glBindRenderbufferOES", &hits); }
void glBlendFuncSeparate(void)
{ static unsigned int hits; tad_gl_stub_hit("glBlendFuncSeparate", &hits); }
GLenum glCheckFramebufferStatusOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glCheckFramebufferStatusOES", &hits); return 0; }
void glClearDepthfOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glClearDepthfOES", &hits); }
void glClipPlanef(void)
{ static unsigned int hits; tad_gl_stub_hit("glClipPlanef", &hits); }
void glClipPlanefOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glClipPlanefOES", &hits); }
void glClipPlanex(void)
{ static unsigned int hits; tad_gl_stub_hit("glClipPlanex", &hits); }
void glCompressedTexSubImage2D(void)
{ static unsigned int hits; tad_gl_stub_hit("glCompressedTexSubImage2D", &hits); }
void glCopyTexImage2D(void)
{ static unsigned int hits; tad_gl_stub_hit("glCopyTexImage2D", &hits); }
void glCopyTexSubImage2D(void)
{ static unsigned int hits; tad_gl_stub_hit("glCopyTexSubImage2D", &hits); }
void glDeleteFramebuffersOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glDeleteFramebuffersOES", &hits); }
void glDeleteRenderbuffersOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glDeleteRenderbuffersOES", &hits); }
void glDepthRangefOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glDepthRangefOES", &hits); }
void glDepthRangex(void)
{ static unsigned int hits; tad_gl_stub_hit("glDepthRangex", &hits); }
void glDrawTexfOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glDrawTexfOES", &hits); }
void glDrawTexfvOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glDrawTexfvOES", &hits); }
void glDrawTexiOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glDrawTexiOES", &hits); }
void glDrawTexivOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glDrawTexivOES", &hits); }
void glDrawTexsOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glDrawTexsOES", &hits); }
void glDrawTexsvOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glDrawTexsvOES", &hits); }
void glDrawTexxOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glDrawTexxOES", &hits); }
void glDrawTexxvOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glDrawTexxvOES", &hits); }
void glFogf(void)
{ static unsigned int hits; tad_gl_stub_hit("glFogf", &hits); }
void glFogfv(void)
{ static unsigned int hits; tad_gl_stub_hit("glFogfv", &hits); }
void glFogx(void)
{ static unsigned int hits; tad_gl_stub_hit("glFogx", &hits); }
void glFogxv(void)
{ static unsigned int hits; tad_gl_stub_hit("glFogxv", &hits); }
void glFramebufferRenderbufferOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glFramebufferRenderbufferOES", &hits); }
void glFramebufferTexture2DOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glFramebufferTexture2DOES", &hits); }
void glGenFramebuffersOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glGenFramebuffersOES", &hits); }
void glGenRenderbuffersOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glGenRenderbuffersOES", &hits); }
void glGenerateMipmapOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glGenerateMipmapOES", &hits); }
void glGetBufferParameteriv(void)
{ static unsigned int hits; tad_gl_stub_hit("glGetBufferParameteriv", &hits); }
void glGetClipPlanef(void)
{ static unsigned int hits; tad_gl_stub_hit("glGetClipPlanef", &hits); }
void glGetClipPlanefOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glGetClipPlanefOES", &hits); }
void glGetClipPlanex(void)
{ static unsigned int hits; tad_gl_stub_hit("glGetClipPlanex", &hits); }
void glGetFramebufferAttachmentParameterivOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glGetFramebufferAttachmentParameterivOES", &hits); }
void glGetLightfv(void)
{ static unsigned int hits; tad_gl_stub_hit("glGetLightfv", &hits); }
void glGetLightxv(void)
{ static unsigned int hits; tad_gl_stub_hit("glGetLightxv", &hits); }
void glGetMaterialfv(void)
{ static unsigned int hits; tad_gl_stub_hit("glGetMaterialfv", &hits); }
void glGetMaterialxv(void)
{ static unsigned int hits; tad_gl_stub_hit("glGetMaterialxv", &hits); }
void glGetPointerv(void)
{ static unsigned int hits; tad_gl_stub_hit("glGetPointerv", &hits); }
void glGetRenderbufferParameterivOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glGetRenderbufferParameterivOES", &hits); }
GLboolean glIsFramebufferOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glIsFramebufferOES", &hits); return 0 /* GL_FALSE */; }
GLboolean glIsRenderbufferOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glIsRenderbufferOES", &hits); return 0 /* GL_FALSE */; }
void glLightModelf(void)
{ static unsigned int hits; tad_gl_stub_hit("glLightModelf", &hits); }
void glLightModelfv(void)
{ static unsigned int hits; tad_gl_stub_hit("glLightModelfv", &hits); }
void glLightModelx(void)
{ static unsigned int hits; tad_gl_stub_hit("glLightModelx", &hits); }
void glLightModelxv(void)
{ static unsigned int hits; tad_gl_stub_hit("glLightModelxv", &hits); }
void glLightf(void)
{ static unsigned int hits; tad_gl_stub_hit("glLightf", &hits); }
void glLightfv(void)
{ static unsigned int hits; tad_gl_stub_hit("glLightfv", &hits); }
void glLightx(void)
{ static unsigned int hits; tad_gl_stub_hit("glLightx", &hits); }
void glLightxv(void)
{ static unsigned int hits; tad_gl_stub_hit("glLightxv", &hits); }
void glLogicOp(void)
{ static unsigned int hits; tad_gl_stub_hit("glLogicOp", &hits); }
void glMaterialf(void)
{ static unsigned int hits; tad_gl_stub_hit("glMaterialf", &hits); }
void glMaterialfv(void)
{ static unsigned int hits; tad_gl_stub_hit("glMaterialfv", &hits); }
void glMaterialx(void)
{ static unsigned int hits; tad_gl_stub_hit("glMaterialx", &hits); }
void glMaterialxv(void)
{ static unsigned int hits; tad_gl_stub_hit("glMaterialxv", &hits); }
void glMultiTexCoord4f(void)
{ static unsigned int hits; tad_gl_stub_hit("glMultiTexCoord4f", &hits); }
void glMultiTexCoord4x(void)
{ static unsigned int hits; tad_gl_stub_hit("glMultiTexCoord4x", &hits); }
void glNormal3f(void)
{ static unsigned int hits; tad_gl_stub_hit("glNormal3f", &hits); }
void glNormal3x(void)
{ static unsigned int hits; tad_gl_stub_hit("glNormal3x", &hits); }
void glOrthofOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glOrthofOES", &hits); }
void glPixelStorei(void)
{ static unsigned int hits; tad_gl_stub_hit("glPixelStorei", &hits); }
void glPointParameterf(void)
{ static unsigned int hits; tad_gl_stub_hit("glPointParameterf", &hits); }
void glPointParameterfv(void)
{ static unsigned int hits; tad_gl_stub_hit("glPointParameterfv", &hits); }
void glPointParameterx(void)
{ static unsigned int hits; tad_gl_stub_hit("glPointParameterx", &hits); }
void glPointParameterxv(void)
{ static unsigned int hits; tad_gl_stub_hit("glPointParameterxv", &hits); }
void glPointSizePointerOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glPointSizePointerOES", &hits); }
GLbitfield glQueryMatrixxOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glQueryMatrixxOES", &hits); return 0xFFFFu; }
void glReadPixels(void)
{ static unsigned int hits; tad_gl_stub_hit("glReadPixels", &hits); }
void glRenderbufferStorageOES(void)
{ static unsigned int hits; tad_gl_stub_hit("glRenderbufferStorageOES", &hits); }
void glSampleCoverage(void)
{ static unsigned int hits; tad_gl_stub_hit("glSampleCoverage", &hits); }
void glSampleCoveragex(void)
{ static unsigned int hits; tad_gl_stub_hit("glSampleCoveragex", &hits); }
