#!/bin/bash
# Tadpole — remove installed system files, returning to a first-run state.
#
#   ./tools/erase-firmware.sh                 the device that is live
#   ./tools/erase-firmware.sh --device ID     one particular device
#   ./tools/erase-firmware.sh --all           every device installed here
#   ./tools/erase-firmware.sh --really-delete   ...and mean it (see below)
#
# For testing the setup wizard, which is otherwise awkward to reach once an
# install works.
#
# ONE DEVICE AT A TIME, BY DEFAULT, and that default changed when several could
# be installed at once. This used to walk every directory under rootfs/ and
# take the lot; with a LeapPad2 and a LeapPad3 side by side, "erase the system
# files" from a menu item that says nothing about which would have thrown away
# the one that was not on screen. The Erase item in the front end erases what
# the front end is showing. --all is still one flag away and says what it does.
#
# IT MOVES RATHER THAN DELETES, by default.
#
# Re-installing needs the firmware packages AND ubi_reader, and if either is
# missing a genuine `rm -rf` leaves you unable to run anything until you sort
# that out. A rename costs nothing and is reversible in one command, so the
# destructive version is opt-in.
#
# Never touches: games/ (your cartridge backups), sources/ (your firmware
# downloads), or anything you built.

set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ="$(dirname "$HERE")"
. "$PROJ/runtime/device.sh"

HARD=0
ALL=0
WANT=""
while [ $# -gt 0 ]; do
    case "$1" in
        --really-delete) HARD=1 ;;
        --all)           ALL=1 ;;
        --device)        shift; WANT="${1:-}" ;;
        --device=*)      WANT="${1#--device=}" ;;
        -h|--help)       sed -n '2,10p' "$0"; exit 0 ;;
        *)  echo "unknown argument: $1" >&2; exit 2 ;;
    esac
    shift || true
done

STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP="$PROJ/.erased-$STAMP"

moved=0
takeaway() {                        # $1 = path to remove
    local rel dest
    [ -e "$1" ] || return 0
    if [ "$HARD" = 1 ]; then
        rm -rf "$1" && echo "  deleted  ${1#$PROJ/}"
    else
        # PRESERVE THE RELATIVE PATH inside the backup, so restoring is a single
        # `cp -a`. Flattening everything into one directory loses where each
        # piece came from — rootfs/<ver> and runtime/sysroot land side by side
        # and the restore command becomes a guess.
        rel="${1#$PROJ/}"
        dest="$BACKUP/$(dirname "$rel")"
        mkdir -p "$dest"
        mv "$1" "$dest/" && echo "  moved    $rel"
    fi
    moved=$((moved+1))
}

# Everything belonging to one DEV_ID: its firmware, and whichever of the two
# places its assembled tree is sitting in.
erase_device() {
    local id="$1" rootfs
    rootfs="$(tad_rootfs_for_device "$id")"
    # The firmware tree, not the emmc_rfs/ubi_rfs inside it: rootfs/<version>/
    # is the unit install-firmware.sh creates and the unit a restore wants.
    [ -n "$rootfs" ] && takeaway "$(dirname "$rootfs")"
    if [ "$id" = "$(tad_active_device)" ]; then
        # GENERATED by setup-sysroot.sh — symlinks into rootfs plus the
        # writable directories the guest needs. Removing it is safe and it is
        # rebuilt. runtime/libs is the same kind of thing and belongs to the
        # same device, so it goes with it rather than being left behind
        # pointing into a rootfs that is no longer there.
        takeaway "$PROJ/runtime/sysroot"
        takeaway "$PROJ/runtime/libs"
    else
        takeaway "$(tad_installs_dir)/$id"
    fi
}

ACTIVE="$(tad_active_device)"

if [ "$ALL" = 1 ]; then
    echo "Erasing ALL installed system files..."
    for d in "$PROJ"/rootfs/*/; do
        [ -d "$d" ] || continue
        takeaway "${d%/}"
    done
    takeaway "$PROJ/runtime/sysroot"
    takeaway "$PROJ/runtime/libs"
    takeaway "$(tad_installs_dir)"
else
    [ -n "$WANT" ] || WANT="$ACTIVE"
    if [ -z "$WANT" ]; then
        echo "  nothing installed — already at a first-run state"
        exit 0
    fi
    echo "Erasing system files for $WANT..."
    erase_device "$WANT"
fi

if [ "$moved" = 0 ]; then
    echo "  nothing installed — already at a first-run state"
    exit 0
fi

# LEAVE A WORKING EMULATOR IF THERE IS ONE LEFT. Erasing the live device with
# another still parked used to be impossible; now it is ordinary, and finishing
# with an empty runtime/sysroot while a perfectly good LeapPad2 sits in
# runtime/installs would present as "erasing one device broke the other".
if [ "$ALL" = 0 ] && [ ! -d "$PROJ/runtime/sysroot" ]; then
    next="$(ls "$(tad_installs_dir)" 2>/dev/null | head -1)"
    if [ -n "$next" ] && tad_activate_device "$next" >/dev/null 2>&1; then
        echo
        echo "Switched to $next, which is still installed."
    fi
fi

echo
if [ "$HARD" = 1 ]; then
    echo "Deleted. Re-install with:  ./tools/install-firmware.sh <LFC_Downloads>"
else
    echo "Moved to: ${BACKUP#$PROJ/}"
    echo "Restore with:   cp -a ${BACKUP#$PROJ/}/. ./ && rm -rf ${BACKUP#$PROJ/}"
    echo "Or re-install:  ./tools/install-firmware.sh <LFC_Downloads>"
fi
[ -d "$PROJ/runtime/sysroot" ] ||
    echo "Tadpole will show the setup wizard on next launch."
