#!/bin/bash
# Tadpole — remove the installed system files, returning to a first-run state.
#
#   ./tools/erase-firmware.sh [--really-delete]
#
# For testing the setup wizard, which is otherwise awkward to reach once an
# install works.
#
# IT MOVES RATHER THAN DELETES, by default.
#
# Re-installing needs the firmware packages AND ubi_reader, and if either is
# missing a genuine `rm -rf` leaves you unable to run anything until you sort
# that out. A rename costs nothing and is reversible in one command, so the
# destructive version is opt-in.
#
# Never touches: games/ (your cartridge backups), sources/ (your firmware
# downloads), or anything you built.

set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ="$(dirname "$HERE")"
HARD=0
[ "${1:-}" = "--really-delete" ] && HARD=1

STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP="$PROJ/.erased-$STAMP"

moved=0
takeaway() {                        # $1 = path to remove
    [ -e "$1" ] || return 0
    if [ "$HARD" = 1 ]; then
        rm -rf "$1" && echo "  deleted  ${1#$PROJ/}"
    else
        mkdir -p "$BACKUP"
        mv "$1" "$BACKUP/" && echo "  moved    ${1#$PROJ/}"
    fi
    moved=$((moved+1))
}

echo "Erasing installed system files..."

# The extracted firmware.
for d in "$PROJ"/rootfs/*/; do
    [ -d "$d" ] || continue
    takeaway "${d%/}"
done

# The sysroot is GENERATED by setup-sysroot.sh — symlinks into rootfs plus the
# writable directories the guest needs. Removing it is safe and it is rebuilt.
takeaway "$PROJ/runtime/sysroot"

if [ "$moved" = 0 ]; then
    echo "  nothing installed — already at a first-run state"
    exit 0
fi

echo
if [ "$HARD" = 1 ]; then
    echo "Deleted. Re-install with:  ./tools/install-firmware.sh <LFC_Downloads>"
else
    echo "Moved to: ${BACKUP#$PROJ/}"
    echo "Restore with:   mv ${BACKUP#$PROJ/}/* ./ && mv rootfs_* rootfs/ 2>/dev/null"
    echo "Or re-install:  ./tools/install-firmware.sh <LFC_Downloads>"
fi
echo "Tadpole will show the setup wizard on next launch."
