#!/usr/bin/env python3
"""Regenerate tadpole_gles_stubs.c so no guest can hit an unresolved symbol.

    ./tools/gen-gl-stubs.py            report only
    ./tools/gen-gl-stubs.py --write    rewrite the stubs file

WHY THIS MATTERS MORE THAN IT USED TO. Our libGLESv1_CM.so is now also reached
under the name libopengles_lite.so, which is what native titles link. Before
that alias they fell through to the stock LeapFrog driver, which exports all 180
GL/EGL entry points — dead, but present, so they always LOADED. Against our
library a single missing entry point is fatal at load time:

    AppManager: can't resolve symbol 'glLightx'

Pet Pals 2 stopped showing its startup logo for exactly that reason. Completeness
of the symbol table is therefore a hard requirement, separate from whether any
given call does anything useful.

A stub is not a fix. It makes the title load and run; a call that needs real
behaviour still needs implementing in tadpole_gles_core.c. The report below
distinguishes the two so the difference stays visible instead of being quietly
papered over.

A STUB IS ALSO NOT SILENT ANY MORE. Every one reports itself the first time it
is called, counts its hits, and appears in the summary the GL library prints
when it unloads. TADPOLE_GL_DEBUG=2 makes the first one FATAL, so the crash
handler's stack scan names the caller. That is the difference between "the
character renders black" and "App.so+0x2f1a4 called glLightfv, which we never
wrote" — see tadpole/shim/tadpole_gles_debug.c.

Which is also why the instrumentation lives HERE, in the template, and not in
the generated file: hand-editing 108 stub bodies would survive exactly until the
next --write.
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
STUBS = os.path.join(PROJ, "tadpole", "shim", "tadpole_gles_stubs.c")
CORE = os.path.join(PROJ, "tadpole", "shim", "tadpole_gles_core.c")
EGL = os.path.join(PROJ, "tadpole", "shim", "tadpole_egl.c")

# Entry points that must do real work for 3D to be correct. Stubbing them keeps
# a title running but renders it wrong, so they are called out separately.
IMPORTANT = {
    "glFrustumf", "glFrustumx", "glFrustumfOES",
    "glTexEnvf", "glTexEnvi", "glTexEnviv",
    "glNormal3f", "glNormal3x",
    "glGetFloatv", "glGetBooleanv",
    "glLightx", "glLightfv", "glLightxv",
    "glMaterialf", "glMaterialfv",
    "glMultiTexCoord4f", "glMultiTexCoord4x",
    "glDepthRangex", "glClearDepthfOES",
    "glColor4f", "glCullFace", "glScissor", "glShadeModel",
    "glNormalPointer", "glReadPixels", "glTexEnvfv",
    "glPixelStorei", "glHint", "glFinish",
}

# ENTRY POINTS THAT RETURN A VALUE.
#
# `void glFoo(void) { }` does not just ignore its arguments — it also leaves
# whatever happened to be in r0 as the caller's return value. For a function the
# caller reads, that is worse than useless: glCheckFramebufferStatusOES handing
# back a stale pointer looks like a valid-but-unrecognised status, and a title
# that loops until the framebuffer is complete never stops. Give each one a
# DEFINED answer, chosen to be the honest one for a feature we have not built.
#
# Anything not listed here is emitted as void, which is correct for the ~170
# GLES 1.1 entry points that genuinely return nothing.
RETURNS = {
    # 0 is the spec's own "the query failed" answer, and it is true here.
    "glCheckFramebufferStatusOES": ("GLenum", "0"),
    # We have never created one, so GL_FALSE is not a placeholder — it is right.
    "glIsFramebufferOES":  ("GLboolean", "0 /* GL_FALSE */"),
    "glIsRenderbufferOES": ("GLboolean", "0 /* GL_FALSE */"),
    # Bit i set means "component i is not a valid fixed-point number". This stub
    # writes no components at all, so every one of the 16 is invalid, and saying
    # so is what stops a caller trusting the uninitialised array it passed in.
    "glQueryMatrixxOES": ("GLbitfield", "0xFFFFu"),
}


HEADER = '''/* Tadpole — GLES 1.x entry points we have not implemented.
 *
 * GENERATED by tools/gen-gl-stubs.py — do not edit by hand. To change what a
 * stub does, change the template in that script; a hand edit here survives
 * exactly until the next `gen-gl-stubs.py --write`.
 *
 * These exist so a guest can never hit an unresolved symbol. Since our library
 * is reached as libopengles_lite.so, which is the name native titles link, a
 * missing entry point is fatal at LOAD time:
 *     AppManager: can't resolve symbol 'glLightx'
 * Real implementations live in tadpole_gles_core.c and take precedence;
 * anything left here does no GL work at all.
 *
 * WHAT THEY DO INSTEAD OF NOTHING. Each one counts its calls and says so — once
 * at any volume, every time under TADPOLE_GL_DEBUG=1, and fatally under
 * TADPOLE_GL_DEBUG=2. The count matters as much as the name: it turns "108
 * entry points are missing" into "this title called these six, 1200 times a
 * frame", which is the difference between a list and a work queue.
 *
 * They still take no arguments. That is deliberate and it is safe: the caller
 * cleans up its own stack under AAPCS, so a (void) callee simply ignores
 * whatever was passed. It is also why a stub can never USE those arguments —
 * implementing one means moving it to tadpole_gles_core.c with a real
 * signature, not filling in a body here.
 */
#include "tadpole_gles_debug.h"

typedef unsigned int  GLenum;
typedef unsigned int  GLbitfield;
typedef unsigned char GLboolean;

'''


def device_symbols():
    """Every gl*/egl* entry point the real device's library exports."""
    for root in (os.path.expanduser("~/.local/share/tadpole/rootfs"),
                 os.path.join(PROJ, "rootfs")):
        for dirpath, _, files in os.walk(root):
            for f in files:
                if f.startswith("libGLESv1_CM.so"):
                    p = os.path.join(dirpath, f)
                    if os.path.islink(p):
                        continue
                    out = subprocess.run(
                        ["readelf", "--dyn-syms", "-W", p],
                        capture_output=True, text=True).stdout
                    syms = set()
                    for line in out.splitlines():
                        parts = line.split()
                        if len(parts) >= 8 and parts[3] == "FUNC" \
                                and parts[6] != "UND":
                            n = parts[7].split("@")[0]
                            if n.startswith(("gl", "egl")):
                                syms.add(n)
                    if syms:
                        return syms, p
    return set(), None


def strip_noncode(src):
    """Remove comments and string literals, keeping byte offsets meaningless.

    THIS IS NOT TIDINESS, IT IS CORRECTNESS. The definition regex below allows
    an argument list to span newlines, and stops only at ';' or '{'. Prose
    contains neither, so a COMMENT mentioning a call — tadpole_gles_core.c has
    one reading "1156 glEnable(GL_TEXTURE_2D) against 365 glDisable in one Clam
    Prix run" — opens a match that runs until the next '){' anywhere in the
    file. Measured: 2251 characters, straight across the real definition of
    glGetIntegerv, which the scan then reported as NOT implemented. --write duly
    emitted a stub for it, and the build failed with a duplicate symbol.

    The failure mode is the bad one: editing a COMMENT silently changes which
    entry points this script believes exist.
    """
    out, i, n = [], 0, len(src)
    while i < n:
        c = src[i]
        if c == "/" and i + 1 < n and src[i + 1] == "*":
            j = src.find("*/", i + 2)
            i = n if j < 0 else j + 2
            out.append(" ")
        elif c == "/" and i + 1 < n and src[i + 1] == "/":
            j = src.find("\n", i)
            i = n if j < 0 else j
            out.append(" ")
        elif c in "\"'":
            q, i = c, i + 1
            while i < n and src[i] != q:
                i += 2 if src[i] == "\\" else 1
            i += 1
            out.append(" ")
        else:
            out.append(c)
            i += 1
    return "".join(out)


def defined_in(path):
    """Entry points with a real definition in a source file."""
    try:
        src = open(path, errors="replace").read()
    except OSError:
        return set()
    # A definition is a return type, the name, an argument list, then a brace.
    return set(re.findall(r"\b((?:gl|egl)[A-Za-z0-9_]*)\s*\([^;{]*\)\s*\{",
                          strip_noncode(src)))


def stub_names():
    return defined_in(STUBS)


def exported_by_us():
    """What our BUILT library actually exports — ground truth.

    The source-scanning regex above is only good enough to tell a real
    implementation from a stub; it misses definitions whose formatting it does
    not anticipate, and acting on that would emit a stub for something already
    defined and break the link with a duplicate symbol. The symbol table cannot
    be wrong about what exists.
    """
    lib = os.path.join(PROJ, "runtime", "shimlibs-gl", "libGLESv1_CM.so")
    if not os.path.exists(lib):
        return None
    out = subprocess.run(["readelf", "--dyn-syms", "-W", lib],
                         capture_output=True, text=True).stdout
    syms = set()
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 8 and parts[3] == "FUNC" and parts[6] != "UND":
            n = parts[7].split("@")[0]
            if n.startswith(("gl", "egl")):
                syms.add(n)
    return syms


def main(argv):
    write = "--write" in argv
    dev, devpath = device_symbols()
    if not dev:
        sys.stderr.write("gen-gl-stubs: no device libGLESv1_CM.so found\n")
        return 1

    real_src = defined_in(CORE) | defined_in(EGL)
    real = real_src
    stubs = stub_names()
    built = exported_by_us()
    if built is None:
        # NOT FATAL, because the moment this matters most is the moment the
        # library does not exist. Implementing an entry point in the core makes
        # the next build fail with a duplicate symbol, lld deletes its output,
        # and the fix is to run exactly this script — which used to refuse,
        # saying "build the GL shim first". A deadlock with a confident error
        # message. The symbol table is better ground truth when it is there, so
        # say what is being given up rather than pretending nothing changed.
        sys.stderr.write("gen-gl-stubs: no built library at runtime/shimlibs-gl"
                         " — falling back to the source scan.\n"
                         "  'MISSING ENTIRELY' below is only as good as the"
                         " regex; rerun after a successful build to confirm.\n\n")
        have = real_src | stubs
        real = real_src
    else:
        # What EXISTS comes from the symbol table; the source scan only
        # classifies what exists into real-vs-stub.
        have = built | stubs
        real = real & built
    missing = sorted(dev - have)
    stubbed_important = sorted((stubs & IMPORTANT) - real)

    print("device exports        %d" % len(dev))
    print("  real implementations %d  (tadpole_gles_core.c, tadpole_egl.c)"
          % len(real & dev))
    print("  no-op stubs          %d" % len(stubs & dev))
    print("  MISSING ENTIRELY     %d  <- these fail to LOAD" % len(missing))
    print()
    if missing:
        print("missing:")
        for i in range(0, len(missing), 4):
            print("   " + "  ".join("%-28s" % m for m in missing[i:i + 4]))
        print()
    if stubbed_important:
        print("stubbed but NEEDED for correct rendering (a stub loads, then")
        print("draws the wrong thing — implement these in the core):")
        for i in range(0, len(stubbed_important), 3):
            print("   " + "  ".join("%-26s" % m
                                    for m in stubbed_important[i:i + 3]))
        print()

    if not write:
        print("(report only; pass --write to regenerate the stubs file)")
        return 0

    # DROP ANYTHING THAT NOW HAS A REAL IMPLEMENTATION.
    #
    # This used to keep every existing stub unconditionally, so implementing an
    # entry point in the core and regenerating produced a stub AND a definition:
    #
    #     ld.lld: error: duplicate symbol: glGetFloatv
    #
    # ...which is a link failure, not a silent one, but it made "implement it,
    # then rerun --write" fail in a way that looks like the generator is broken
    # rather than like the last step of the documented workflow.
    #
    # The source scan is used here rather than `real` (which is intersected with
    # the BUILT library) on purpose: after adding a definition the build has not
    # succeeded yet, so the built symbol table still calls it a stub. The risk
    # runs the other way — a definition the regex fails to recognise keeps its
    # stub, and the duplicate-symbol error above says so immediately.
    moved = sorted(stubs & real_src)
    keep = sorted(stubs - real_src)
    body = keep + missing
    if moved:
        print("no longer stubs (now implemented in the core):")
        for i in range(0, len(moved), 3):
            print("   " + "  ".join("%-26s" % m for m in moved[i:i + 3]))
        print()
    with open(STUBS, "w") as fh:
        fh.write(HEADER)
        for n in body:
            ret = RETURNS.get(n)
            fh.write("%s %s(void)\n{ static unsigned int hits;"
                     " tad_gl_stub_hit(\"%s\", &hits);%s }\n"
                     % (ret[0] if ret else "void", n, n,
                        " return %s;" % ret[1] if ret else ""))
    print("wrote %s (%d entry points)" % (STUBS, len(body)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
